version: '3'

services:
    nginx:
        build: nginx
        restart: always
        links:
            - php
        ports:
            - "80:80"
        volumes:
            - "./:/code"

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_DATABASE: url_parser
            MYSQL_USER: url_parser
            MYSQL_PASSWORD: url_parser
        volumes:
            - "./database/origin:/var/lib/mysql"
        ports:
            - '33061:3306'

    php:
        image: mysterybrand/php-fpm
        restart: always
        user: '${RUN_CONTAINER_WITH_USER}'
        working_dir: '/code'
        volumes:
            - "./:/code"
        links:
            - mysql